### ISSUE TITLE
質問：btreeに100MBのvalueを書いたらどうなるんですか？

### ISSUE THREAD

**Issue by akiradeveloper** [KOBA789/relly#1]
WEB+DBプレスの記事を４章まで読んでわからないところがあったのでコードを読んでますが、やっぱりわからなかったです。

仮にすごく大きなサイズのvalue（例えば100MB）を書き込んだ場合、どういう動作になるんでしょうか？あるいは、今実装していないとしても、どういう動作になるのが一般的なんでしょうか？

**Comment by KOBA789** [comment]
非常にいい質問です！

結論から言いますと、現状の relly ではページサイズを超える値を書き込むことは「できません」。
ページサイズを超える大きな値を格納するには追加の実装が必要です。

ページサイズを超えるほどの大きな値をヒープファイルに格納する方法はいくつかあります。
アイデアのひとつを簡単に紹介しますと、大きなデータをページに収まる大きさのいくつかのブロックに分割し、B-Tree のリーフノードにはそのブロックへのポインタのみを格納する方法があります。
ブロック同士は単方向の連結リストにしておいて、値を取り出すときはそれを辿ればいいでしょう。

実際の実装ですと、たとえば PostgreSQL では TOAST と呼ばれる方法で実現しています。
https://www.postgresql.jp/document/12/html/storage-toast.html

このあたりは各 RDBMS ごとにデータ構造・アルゴリズムや制限が分かれるところですので、それぞれの RDBMS のマニュアルやコードを読んで比較するとおもしろい部分かと思います。
また、RDBMS のカラムに巨大なデータ(画像や動画など)を入れてはならない(入れるとパフォーマンスが悪い)と言われる理由もこのあたりの仕組みに由来しています。
ぜひ調べてみてください。

**Comment by akiradeveloper** [comment]
ユーザ側でkey-0,1,2,...とインデックスを振って分割してあげるという方法もあるのかなと思ってました。

理解しました。
