### ISSUE TITLE
質問 : LayoutVerfiedのアラインメントについて

### ISSUE THREAD

**Issue by dum-601** [KOBA789/relly#11]
WEB+DB PRESSの記事を見て、rellyの実装について学んでいるものです。記事の内容・コードともに非常に勉強になっています。今回は、実装について(少し細かい点ですが)質問したいことがあり、issueを立てさせていただきました。
rellyのコードでは、```Leaf```や```Branch```のコンストラクタ(```Leaf::new```や```Branch::new```)にバイト列の参照(```&[u8]```や```Rc<[u8]>```)を渡し、初期化しています。この際、new関数の内部ではそのバイト列の参照(コードに則りbytesと呼びます)を```LayoutVerified::new_from_prefix```に渡すわけですが、このとき```bytes```が参照する配列のアラインメントが正しいことは保証されるのでしょうか？
例えば、[```Leaf```の実装](https://github.com/KOBA789/relly/blob/9094b86b14edc262356184987f48329ea314f72f/src/btree/leaf.rs#L17)を見てみると、```Leaf```構造体の```header```メンバは```LayoutVerified<B, Header>```型なので、```bytes```が参照する配列は```Header```のアラインメントである8の倍数のアドレスにアラインメントされていなければならないと思います。(参考：[new_from_prefixの仕様](https://docs.rs/zerocopy/latest/zerocopy/struct.LayoutVerified.html#method.new_from_prefix))しかし、bytesが参照する配列は```[u8]```なので、そのアラインメントは1であり、8の倍数のアドレスにアラインメントされることが保証されないように思えています。(コードが正しく動いているので、実際は正しくアラインメントされているようですが・・・)

**Comment by KOBA789** [comment]
質問ありがとうございます。

> このときbytesが参照する配列のアラインメントが正しいことは保証されるのでしょうか？

いい質問ですね。結論から書きますと、`LayoutVerified::new_from_prefix` に渡す前の `bytes` が8バイトでアラインされている保証はどこにもありません。

まとめると次のようになります:
- `LayoutVerified::new_from_prefix` 以前にアラインメントの保証はない
- もしアラインメントが整合しなければ `LayoutVerified::new_from_prefix(bytes).expect(...)` で実行時に panic する
- `LayoutVerified::new_from_prefix` 以後はアラインメントの保証がある
- 現状 panic せずに動いているのは「偶然」で、アロケーターの実装の詳細に依存している
- 正しく panic するので safe ではあるが、お行儀のいいコードとはいえない

たとえば、お行儀よくするにはつぎのような実装が考えられます。
まず、[`Page` の定義](https://github.com/KOBA789/relly/blob/9094b86b14edc262356184987f48329ea314f72f/src/buffer.rs#L20)を type alias ではなく struct にし、`#[repr(align(N))]` attribute を付けます。
```rust
#[repr(align(8))]
pub struct Page([u8; PAGE_SIZE]);
```

次に、この `Page` struct に `Deref<Target = [u8]> + DerefMut` を実装します。
```rust
impl Deref for Page {
  type Target = [u8];
  /* blah blah */
}
impl DerefMut for Page {
  /* blah blah */
}
```

成立性をまったく精査していませんが、以上のような方針でうまくいくような気がします。
もし試す機会があったらぜひ結果を教えてください！

**Comment by dum-601** [comment]
なるほど、納得しました！　ご提案いただいたコードの改善案も含め、いろいろコードをいじって遊んでみようと思います。　ありがとうございます！
