### ISSUE TITLE
カーネルランドRDBMS

### ISSUE THREAD

**Issue by kazuminn** [KOBA789/relly#2]
あんまり関係ないですけど、
これはユーザランドのRDBMSですけど、カーネルランドのRDBMSとか存在するのですか？

**Comment by KOBA789** [comment]
私の知っている範囲では、カーネルランドで動く RDBMS の例は思いつきませんでした。
ただし、Relational でこそないですが（また DBMS の定義にもよりますが）、ファイルシステムは一種の DBMS と呼べるかもしれません。

もしカーネルランドで動く RDBMS を発見したらぜひ教えてください。あるとしたらどういう用途なのかもとても気になりますね。

**Comment by KOBA789** [comment]
開けっぱなしにしておくとノイジーなのでひとまず閉じますね。
また質問等あればぜひ気軽に issue を立ててください。
