### ISSUE TITLE
質問: `RC::clone( )`と`.clone()`について

### ISSUE THREAD

**Issue by h3y6e** [KOBA789/relly#4]
RDBMSについての素晴らしい教材を作成していただきありがとうございます。

Rustを普段から触っているわけではないため不躾な質問で恐縮ですが、
https://github.com/KOBA789/relly/blob/2fd75c1cf5d8ce16c065f01f43a5c5205dbb9f7c/src/buffer.rs#L127
が
```rust
return Ok(Rc::clone(&frame.buffer));
```
と記述されていないのは何か意図があるのでしょうか？

自分の理解としては`Rc::clone( )`と`.clone()`は同値であると認識しており、同ファイルの他の行(143行, 167行)では`Rc::clone(&frame.buffer)`を用いられていたので気になった次第です。

**Comment by KOBA789** [comment]
おっと、ナイスキャッチです。
これは単純な表記揺れですね。

> 自分の理解としてはRc::clone( )と.clone()は同値であると認識しており、

おっしゃるとおりです。

deep clone ではないことをハッキリさせるために、あえて `Rc::clone` と書くようにしたつもりだったのですが、漏れていたようです。
ご指摘ありがとうございます。修正しておきます。

**Comment by h3y6e** [comment]
なるほど、承知いたしました。
素早い返信・対応をありがとうございます。

**Comment by KOBA789** [comment]
Fixed in: 032c68da4eeb4cade3f24785dd93cf814029dafe
