### ISSUE TITLE
`BTree`に`insert`した値が`search`で取得できない

### ISSUE THREAD

**Issue by hatoo** [KOBA789/relly#6]
https://github.com/KOBA789/relly/compare/wdb...hatoo:btree-add-random-test

にランダムな長さのデータを`insert`して`iter`と`search`でちゃんと値が入っているかを確かめるテストを書いてみたのですがテストに失敗してしまいます。

テストが間違っていたらすいません。

**Comment by KOBA789** [comment]
報告ありがとうございます。
いやな予感がしますね。パッチ読んでみます。

**Comment by KOBA789** [comment]
見事に実装がバグってました……

d6595a4 で修正しました。
